alias ls='ls --color=auto --group-directories-first'
alias gpuinfo='lspci -k | grep -EA1 "VGA|3D|Display"'
alias refind-config='sudo vim /efi/EFI/refind/refind.conf'
alias vi='vim'
alias grep='grep --color=auto'
alias untar='tar xvf'
alias memmon='watch -n 1 free -h'
alias swapflush='sudo swapoff -av && sudo swapon -av'
alias pagecacheflush='echo 1 | sudo tee /proc/sys/vm/drop_caches >/dev/null; echo "Page cache dropped"'
alias myip='curl icanhazip.com'
#alias primerun='__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia '
alias bash-config='vim ~/.bashrc'
#alias zsh-config='vim ~/.zshrc'
alias dotfiles='git --git-dir=$HOME/.lab/git/dotfiles --work-tree=$HOME'
alias homestead='cd $HOME/.lab/vagrant-machines/laravel-homestead; vagrant'
