#!/usr/bin/env python

import subprocess
import sys
from pathlib import Path


output_path = Path('~/.config/hypr/hyprland.d/env_vars.conf').expanduser()

# get systemd-user environment variables
cmd = '/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator'
env_vars = subprocess.check_output([cmd], text=True).strip().replace('"', '').split('\n')

# convert to Hyprland environment variable format
output = '# This file is automatically generated on each login; do not modify\n'
for var in env_vars:
    output += f"env = {var.replace('=', ',')}\n"

# check if environment variables have been updated; if not, no need to continue
if output_path.exists():
    old_output = open(output_path).read()
    if output == old_output:
        sys.exit()

# save to file (which is to be included by Hyprland config)
file = open(output_path, 'w')
file.write(output)
file.close()

# notify user
subprocess.run([
    'notify-send', '-u', 'critical', 'Environment Variables Updated',
    'Please re-login to apply the updated environment variables'
])

